services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
    environment:
      - DB_HOST=postgres
      - MINIO_DOMAIN=minio:9000
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
      - ./infra/create_buckets.sh:/usr/bin/create_buckets.sh
    entrypoint: |
      sh -c "
      minio server --console-address ':9001' /data &
      MINIO_PID=$$!
      sleep 5
      /bin/sh /usr/bin/create_buckets.sh
      wait $$MINIO_PID
      "

volumes:
  postgres_data:
  minio_data: