"""Initial revision

Revision ID: 192a47cc8b64
Revises: cfcbd785eb7c
Create Date: 2024-12-12 19:36:28.699723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192a47cc8b64'
down_revision: Union[str, None] = 'cfcbd785eb7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issuedjwttokens',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issuedjwttokens')
    # ### end Alembic commands ###