"""Initial revision

Revision ID: 329c5868e24b
Revises: 17589653800a
Create Date: 2024-12-12 15:39:52.107362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329c5868e24b'
down_revision: Union[str, None] = '17589653800a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issuedjwttokens',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issuedjwttokens')
    # ### end Alembic commands ###
