"""Initial revision

Revision ID: 9e1d78b8c65c
Revises: 7c1e6d0623f5
Create Date: 2024-12-12 15:32:38.030985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1d78b8c65c'
down_revision: Union[str, None] = '7c1e6d0623f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
